// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCWdHxtYbp4-t1LWx2UNHzFHuvh79PNmw',
    appId: '1:1044341814503:web:3372a62d53d310043b5e42',
    messagingSenderId: '1044341814503',
    projectId: 'myhealthease-db',
    authDomain: 'myhealthease-db.firebaseapp.com',
    storageBucket: 'myhealthease-db.firebasestorage.app',
    measurementId: 'G-WB1JVKMSFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAJS4aXQFltJ3AbQlpAapg9VqPFHkh9bk',
    appId: '1:1044341814503:android:055ea25c3f25feeb3b5e42',
    messagingSenderId: '1044341814503',
    projectId: 'myhealthease-db',
    storageBucket: 'myhealthease-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv7k3OLqwnpu0YUSMR_coLB0Au2CED7Oc',
    appId: '1:1044341814503:ios:62e2e565a79538903b5e42',
    messagingSenderId: '1044341814503',
    projectId: 'myhealthease-db',
    storageBucket: 'myhealthease-db.firebasestorage.app',
    androidClientId: '1044341814503-5q6nvkm3pnj8en865vi8stskkb88gtfm.apps.googleusercontent.com',
    iosClientId: '1044341814503-m212e84iaji8g0gbihuhfjcmbtt2iq8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.healtheaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv7k3OLqwnpu0YUSMR_coLB0Au2CED7Oc',
    appId: '1:1044341814503:ios:62e2e565a79538903b5e42',
    messagingSenderId: '1044341814503',
    projectId: 'myhealthease-db',
    storageBucket: 'myhealthease-db.firebasestorage.app',
    androidClientId: '1044341814503-5q6nvkm3pnj8en865vi8stskkb88gtfm.apps.googleusercontent.com',
    iosClientId: '1044341814503-m212e84iaji8g0gbihuhfjcmbtt2iq8f.apps.googleusercontent.com',
    iosBundleId: 'com.example.healtheaseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCWdHxtYbp4-t1LWx2UNHzFHuvh79PNmw',
    appId: '1:1044341814503:web:0d86929199e9463b3b5e42',
    messagingSenderId: '1044341814503',
    projectId: 'myhealthease-db',
    authDomain: 'myhealthease-db.firebaseapp.com',
    storageBucket: 'myhealthease-db.firebasestorage.app',
    measurementId: 'G-7RYXW6YGR3',
  );

}